# Packages the compiled create-link Lambda code into a deployment ZIP archive.
data "archive_file" "create_link_code" {
  # Create a ZIP-formatted Lambda deployment package.
  type = "zip"

  # Package the JavaScript generated from src/create-link/index.ts.
  source_file = "${path.module}/../../dist/create-link/index.js"

  # Store the generated deployment archive with the compiled function.
  output_path = "${path.module}/../../dist/create-link/function.zip"
}

# Creates the Lambda function responsible for generating and storing short links.
resource "aws_lambda_function" "create_link" {
  # Use the caller-provided name for the deployed Lambda function.
  function_name = var.create_lambda_name

  # Upload the ZIP archive generated by the archive_file data source.
  filename = data.archive_file.create_link_code.output_path

  # Redeploy the function whenever the deployment package contents change.
  source_code_hash = data.archive_file.create_link_code.output_base64sha256

  # Execute the function using the create-link Lambda IAM role.
  role = aws_iam_role.create_link_lambda_role.arn

  # Invoke the exported handler function from the compiled index.js file.
  handler = "index.handler"

  # Execute the function using the Node.js 22.x Lambda runtime.
  runtime = "nodejs22.x"

  # Limit each Lambda invocation to five seconds.
  timeout = 5

  # Provide the DynamoDB table name to the Lambda at runtime.
  environment {
    variables = {
      DYNAMODB_TABLE_NAME = aws_dynamodb_table.link_records.name
    }
  }
}

# Packages the compiled resolve-link Lambda code into a deployment ZIP archive.
data "archive_file" "get_link_record_code" {
  # Create a ZIP-formatted Lambda deployment package.
  type = "zip"

  # Package the JavaScript generated from src/resolve-link/index.ts.
  source_file = "${path.module}/../../dist/resolve-link/index.js"

  # Store the generated deployment archive with the compiled function.
  output_path = "${path.module}/../../dist/resolve-link/function.zip"
}

# Creates the Lambda function responsible for resolving short codes.
resource "aws_lambda_function" "get_link_record" {
  # Use the caller-provided name for the deployed Lambda function.
  function_name = var.resolve_lambda_name

  # Upload the ZIP archive generated by the archive_file data source.
  filename = data.archive_file.get_link_record_code.output_path

  # Redeploy the function whenever the deployment package contents change.
  source_code_hash = data.archive_file.get_link_record_code.output_base64sha256

  # Execute the function using the resolve-link Lambda IAM role.
  role = aws_iam_role.get_link_record_lambda_role.arn

  # Invoke the exported handler function from the compiled index.js file.
  handler = "index.handler"

  # Execute the function using the Node.js 22.x Lambda runtime.
  runtime = "nodejs22.x"

  # Limit each Lambda invocation to five seconds.
  timeout = 5

  # Provide the DynamoDB table name to the Lambda at runtime.
  environment {
    variables = {
      DYNAMODB_TABLE_NAME = aws_dynamodb_table.link_records.name
    }
  }

}
