# Execution role assumed by the create-link Lambda function.
resource "aws_iam_role" "create_link_lambda_role" {
  # Assign a descriptive name to the Lambda execution role.
  name = "create_link_lambda_execution_role"

  # Allow the AWS Lambda service to assume this execution role.
  assume_role_policy = jsonencode({
    Version = "2012-10-17"

    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"

        # Restrict role assumption to the AWS Lambda service.
        Principal = {
          Service = "lambda.amazonaws.com"
        }
      }
    ]
  })
}

# Grants the create-link Lambda permission to write logs to CloudWatch.
resource "aws_iam_role_policy_attachment" "create_link_lambda_logs" {
  # Attach the policy to the create-link Lambda execution role.
  role = aws_iam_role.create_link_lambda_role.name

  # AWS-managed policy providing the basic permissions required for Lambda logging.
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

# Packages the compiled create-link Lambda code into a deployment ZIP archive.
data "archive_file" "create_link_code" {
  # Create a ZIP-formatted Lambda deployment package.
  type = "zip"

  # Package the JavaScript generated from src/create-link/index.ts.
  source_file = "${path.module}/../../dist/create-link/index.js"

  # Store the generated deployment archive with the compiled function.
  output_path = "${path.module}/../../dist/create-link/function.zip"
}

# Creates the Lambda function responsible for generating and storing short links.
resource "aws_lambda_function" "create_link" {
  # Use the caller-provided name for the deployed Lambda function.
  function_name = var.create_lambda_name

  # Upload the ZIP archive generated by the archive_file data source.
  filename = data.archive_file.create_link_code.output_path

  # Redeploy the function whenever the deployment package contents change.
  source_code_hash = data.archive_file.create_link_code.output_base64sha256

  # Execute the function using the create-link Lambda IAM role.
  role = aws_iam_role.create_link_lambda_role.arn

  # Invoke the exported handler function from the compiled index.js file.
  handler = "index.handler"

  # Execute the function using the Node.js 22.x Lambda runtime.
  runtime = "nodejs22.x"

  # Limit each Lambda invocation to five seconds.
  timeout = 5
}


# Execution role assumed by the resolve-link Lambda function.
resource "aws_iam_role" "get_link_record_lambda_role" {
  # Assign a descriptive name to the Lambda execution role.
  name = "get_link_record_lambda_execution_role"

  # Allow the AWS Lambda service to assume this execution role.
  assume_role_policy = jsonencode({
    Version = "2012-10-17"

    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"

        # Restrict role assumption to the AWS Lambda service.
        Principal = {
          Service = "lambda.amazonaws.com"
        }
      }
    ]
  })
}

# Grants the resolve-link Lambda permission to write logs to CloudWatch.
resource "aws_iam_role_policy_attachment" "get_link_record_lambda_logs" {
  # Attach the policy to the resolve-link Lambda execution role.
  role = aws_iam_role.get_link_record_lambda_role.name

  # AWS-managed policy providing the basic permissions required for Lambda logging.
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

# Packages the compiled resolve-link Lambda code into a deployment ZIP archive.
data "archive_file" "get_link_record_code" {
  # Create a ZIP-formatted Lambda deployment package.
  type = "zip"

  # Package the JavaScript generated from src/resolve-link/index.ts.
  source_file = "${path.module}/../../dist/resolve-link/index.js"

  # Store the generated deployment archive with the compiled function.
  output_path = "${path.module}/../../dist/resolve-link/function.zip"
}

# Creates the Lambda function responsible for resolving short codes.
resource "aws_lambda_function" "get_link_record" {
  # Use the caller-provided name for the deployed Lambda function.
  function_name = var.resolve_lambda_name

  # Upload the ZIP archive generated by the archive_file data source.
  filename = data.archive_file.get_link_record_code.output_path

  # Redeploy the function whenever the deployment package contents change.
  source_code_hash = data.archive_file.get_link_record_code.output_base64sha256

  # Execute the function using the resolve-link Lambda IAM role.
  role = aws_iam_role.get_link_record_lambda_role.arn

  # Invoke the exported handler function from the compiled index.js file.
  handler = "index.handler"

  # Execute the function using the Node.js 22.x Lambda runtime.
  runtime = "nodejs22.x"

  # Limit each Lambda invocation to five seconds.
  timeout = 5
}

# Creates the DynamoDB table used to store shortened-link records.
resource "aws_dynamodb_table" "link_records" {
  # Use the caller-provided name for the DynamoDB table.
  name = var.dynamodb_table_name

  # Use on-demand capacity so DynamoDB automatically handles request throughput.
  billing_mode = "PAY_PER_REQUEST"

  # Use the generated short code as the table's partition key.
  hash_key = "code"

  # Define the string attribute used as the partition key.
  attribute {
    name = "code"
    type = "S"
  }

  # Enable automatic cleanup of expired items using the expiration timestamp.
  ttl {
    attribute_name = "expires_at"
    enabled        = true
  }

  # Apply the caller-provided tags to the DynamoDB table.
  tags = var.tags
}


# Creates the API Gateway HTTP API that exposes the URL-shortener endpoints.
resource "aws_apigatewayv2_api" "url_shortener_api" {
  # Use the caller-provided name for the HTTP API.
  name = var.api_gateway_name

  # Configure API Gateway to use the HTTP API protocol.
  protocol_type = "HTTP"

  # Apply the caller-provided tags to the API.
  tags = var.tags
}

# Connects the POST /links route to the create-link Lambda function.
resource "aws_apigatewayv2_integration" "create_link" {
  # Associate this integration with the URL-shortener HTTP API.
  api_id = aws_apigatewayv2_api.url_shortener_api.id

  # Use Lambda proxy integration so requests are forwarded directly to Lambda.
  integration_type = "AWS_PROXY"

  # Invoke the create-link Lambda function for this integration.
  integration_uri = aws_lambda_function.create_link.invoke_arn

  # Use the HTTP API version 2.0 Lambda event format.
  payload_format_version = "2.0"
}

# Routes authenticated POST /links requests to the create-link Lambda integration.
resource "aws_apigatewayv2_route" "create_link" {
  # Associate this route with the URL-shortener HTTP API.
  api_id = aws_apigatewayv2_api.url_shortener_api.id

  # Match POST requests sent to /links.
  route_key = "POST /links"

  # Require AWS IAM authorization for link creation.
  authorization_type = "AWS_IAM"

  # Send matching requests to the create-link Lambda integration.
  target = "integrations/${aws_apigatewayv2_integration.create_link.id}"
}


# Connects the GET /{code} route to the get_link_record Lambda function.
resource "aws_apigatewayv2_integration" "get_link_record" {
  # Associate this integration with the URL-shortener HTTP API.
  api_id = aws_apigatewayv2_api.url_shortener_api.id

  # Use Lambda proxy integration so requests are forwarded directly to Lambda.
  integration_type = "AWS_PROXY"

  # Invoke the get_link_record Lambda function for this integration.
  integration_uri = aws_lambda_function.get_link_record.invoke_arn

  # Use the HTTP API version 2.0 Lambda event format.
  payload_format_version = "2.0"
}

# Routes public GET /{code} requests to the get_link_record Lambda integration.
resource "aws_apigatewayv2_route" "get_link_record" {
  # Associate this route with the URL-shortener HTTP API.
  api_id = aws_apigatewayv2_api.url_shortener_api.id

  # Match GET requests sent to /{code}.
  route_key = "GET /{code}"

  # Send matching requests to the get_link_record Lambda integration.
  target = "integrations/${aws_apigatewayv2_integration.get_link_record.id}"
}
