# Execution role assumed by the create-link Lambda function.
resource "aws_iam_role" "create_link_lambda_role" {
  # Assign a descriptive name to the Lambda execution role.
  name = "create_link_lambda_execution_role"

  # Allow the AWS Lambda service to assume this execution role.
  assume_role_policy = jsonencode({
    Version = "2012-10-17"

    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"

        # Restrict role assumption to the AWS Lambda service.
        Principal = {
          Service = "lambda.amazonaws.com"
        }
      }
    ]
  })
}

# Grants the create-link Lambda permission to write logs to CloudWatch.
resource "aws_iam_role_policy_attachment" "create_link_lambda_logs" {
  # Attach the policy to the create-link Lambda execution role.
  role = aws_iam_role.create_link_lambda_role.name

  # AWS-managed policy providing the basic permissions required for Lambda logging.
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

# Packages the compiled create-link Lambda code into a deployment ZIP archive.
data "archive_file" "create_link_code" {
  # Create a ZIP-formatted Lambda deployment package.
  type = "zip"

  # Package the JavaScript generated from src/create-link/index.ts.
  source_file = "${path.module}/../../dist/create-link/index.js"

  # Store the generated deployment archive with the compiled function.
  output_path = "${path.module}/../../dist/create-link/function.zip"
}

# Creates the Lambda function responsible for generating and storing short links.
resource "aws_lambda_function" "create_link" {
  # Use the caller-provided name for the deployed Lambda function.
  function_name = var.create_lambda_name

  # Upload the ZIP archive generated by the archive_file data source.
  filename = data.archive_file.create_link_code.output_path

  # Redeploy the function whenever the deployment package contents change.
  source_code_hash = data.archive_file.create_link_code.output_base64sha256

  # Execute the function using the create-link Lambda IAM role.
  role = aws_iam_role.create_link_lambda_role.arn

  # Invoke the exported handler function from the compiled index.js file.
  handler = "index.handler"

  # Execute the function using the Node.js 22.x Lambda runtime.
  runtime = "nodejs22.x"

  # Limit each Lambda invocation to five seconds.
  timeout = 5

  # Provide the DynamoDB table name to the Lambda at runtime.
  environment {
    variables = {
      DYNAMODB_TABLE_NAME = aws_dynamodb_table.link_records.name
    }
  }
}


# Execution role assumed by the resolve-link Lambda function.
resource "aws_iam_role" "get_link_record_lambda_role" {
  # Assign a descriptive name to the Lambda execution role.
  name = "get_link_record_lambda_execution_role"

  # Allow the AWS Lambda service to assume this execution role.
  assume_role_policy = jsonencode({
    Version = "2012-10-17"

    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"

        # Restrict role assumption to the AWS Lambda service.
        Principal = {
          Service = "lambda.amazonaws.com"
        }
      }
    ]
  })
}

# Grants the resolve-link Lambda permission to write logs to CloudWatch.
resource "aws_iam_role_policy_attachment" "get_link_record_lambda_logs" {
  # Attach the policy to the resolve-link Lambda execution role.
  role = aws_iam_role.get_link_record_lambda_role.name

  # AWS-managed policy providing the basic permissions required for Lambda logging.
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

# Packages the compiled resolve-link Lambda code into a deployment ZIP archive.
data "archive_file" "get_link_record_code" {
  # Create a ZIP-formatted Lambda deployment package.
  type = "zip"

  # Package the JavaScript generated from src/resolve-link/index.ts.
  source_file = "${path.module}/../../dist/resolve-link/index.js"

  # Store the generated deployment archive with the compiled function.
  output_path = "${path.module}/../../dist/resolve-link/function.zip"
}

# Creates the Lambda function responsible for resolving short codes.
resource "aws_lambda_function" "get_link_record" {
  # Use the caller-provided name for the deployed Lambda function.
  function_name = var.resolve_lambda_name

  # Upload the ZIP archive generated by the archive_file data source.
  filename = data.archive_file.get_link_record_code.output_path

  # Redeploy the function whenever the deployment package contents change.
  source_code_hash = data.archive_file.get_link_record_code.output_base64sha256

  # Execute the function using the resolve-link Lambda IAM role.
  role = aws_iam_role.get_link_record_lambda_role.arn

  # Invoke the exported handler function from the compiled index.js file.
  handler = "index.handler"

  # Execute the function using the Node.js 22.x Lambda runtime.
  runtime = "nodejs22.x"

  # Limit each Lambda invocation to five seconds.
  timeout = 5

  # Provide the DynamoDB table name to the Lambda at runtime.
  environment {
    variables = {
      DYNAMODB_TABLE_NAME = aws_dynamodb_table.link_records.name
    }
  }

}

# Creates the DynamoDB table used to store shortened-link records.
resource "aws_dynamodb_table" "link_records" {
  # Use the caller-provided name for the DynamoDB table.
  name = var.dynamodb_table_name

  # Use on-demand capacity so DynamoDB automatically handles request throughput.
  billing_mode = "PAY_PER_REQUEST"

  # Use the generated short code as the table's partition key.
  hash_key = "short_code"

  # Define the string attribute used as the partition key.
  attribute {
    name = "short_code"
    type = "S"
  }

  # Enable automatic cleanup of expired items using the expiration timestamp.
  ttl {
    attribute_name = "expires_at"
    enabled        = true
  }

  # Apply the caller-provided tags to the DynamoDB table.
  tags = var.tags

  # Encrypt all DynamoDB table data at rest using a customer-managed KMS key.
  server_side_encryption {
    # Enable server-side encryption for the DynamoDB table.
    enabled = true

    # Use this project's customer-managed KMS key instead of an AWS-owned key.
    kms_key_arn = aws_kms_key.dynamodb.arn
  }
}


# Creates the API Gateway HTTP API that exposes the URL-shortener endpoints.
resource "aws_apigatewayv2_api" "url_shortener_api" {
  # Use the caller-provided name for the HTTP API.
  name = var.api_gateway_name

  # Configure API Gateway to use the HTTP API protocol.
  protocol_type = "HTTP"

  # Apply the caller-provided tags to the API.
  tags = var.tags
}

# Connects the POST /links route to the create-link Lambda function.
resource "aws_apigatewayv2_integration" "create_link" {
  # Associate this integration with the URL-shortener HTTP API.
  api_id = aws_apigatewayv2_api.url_shortener_api.id

  # Use Lambda proxy integration so requests are forwarded directly to Lambda.
  integration_type = "AWS_PROXY"

  # Invoke the create-link Lambda function for this integration.
  integration_uri = aws_lambda_function.create_link.invoke_arn

  # Use the HTTP API version 2.0 Lambda event format.
  payload_format_version = "2.0"
}

# Routes authenticated POST /links requests to the create-link Lambda integration.
resource "aws_apigatewayv2_route" "create_link" {
  # Associate this route with the URL-shortener HTTP API.
  api_id = aws_apigatewayv2_api.url_shortener_api.id

  # Match POST requests sent to /links.
  route_key = "POST /links"

  # Require AWS IAM authorization for link creation.
  authorization_type = "AWS_IAM"

  # Send matching requests to the create-link Lambda integration.
  target = "integrations/${aws_apigatewayv2_integration.create_link.id}"
}


# Connects the GET /{code} route to the get_link_record Lambda function.
resource "aws_apigatewayv2_integration" "get_link_record" {
  # Associate this integration with the URL-shortener HTTP API.
  api_id = aws_apigatewayv2_api.url_shortener_api.id

  # Use Lambda proxy integration so requests are forwarded directly to Lambda.
  integration_type = "AWS_PROXY"

  # Invoke the get_link_record Lambda function for this integration.
  integration_uri = aws_lambda_function.get_link_record.invoke_arn

  # Use the HTTP API version 2.0 Lambda event format.
  payload_format_version = "2.0"
}

# Routes public GET /{code} requests to the get_link_record Lambda integration.
resource "aws_apigatewayv2_route" "get_link_record" {
  # Associate this route with the URL-shortener HTTP API.
  api_id = aws_apigatewayv2_api.url_shortener_api.id

  # Match GET requests sent to /{code}.
  route_key = "GET /{code}"

  # Send matching requests to the get_link_record Lambda integration.
  target = "integrations/${aws_apigatewayv2_integration.get_link_record.id}"
}


# Creates the default API Gateway stage used to serve the URL-shortener API.
# Deploys the API so its routes can actually receive requests.
# Using $default makes the API accessible without a stage name in the URL.
resource "aws_apigatewayv2_stage" "default" {
  # Associate this stage with the URL-shortener HTTP API.
  api_id = aws_apigatewayv2_api.url_shortener_api.id

  # Use the special $default stage so requests do not require a stage prefix.
  name = "$default"

  # Automatically deploy API changes to the default stage.
  auto_deploy = true

  # Sends structured API Gateway access logs to the designated CloudWatch log group.
  access_log_settings {
    # Specify the CloudWatch log group that receives the API access logs.
    destination_arn = aws_cloudwatch_log_group.api_gateway_access_logs.arn

    # Format each access log entry as structured JSON without sensitive request data.
    format = jsonencode({
      # Record the unique identifier assigned to the API request.
      request_id = "$context.requestId"

      # Record when API Gateway received the request.
      request_time = "$context.requestTime"

      # Record the HTTP method used for the request.
      http_method = "$context.httpMethod"

      # Record the API route that handled the request.
      route_key = "$context.routeKey"

      # Record the HTTP status code returned to the client.
      status = "$context.status"

      # Record the size of the response returned to the client.
      response_length = "$context.responseLength"
    })
  }
}

# Allows API Gateway to invoke the create-link Lambda function.
resource "aws_lambda_permission" "allow_api_gateway_create_link" {
  # Assign a unique identifier to this Lambda resource-based policy statement.
  statement_id = "AllowAPIGatewayInvokeCreateLink"

  # Permit API Gateway to invoke the Lambda function.
  action = "lambda:InvokeFunction"

  # Grant the permission on the create-link Lambda function.
  function_name = aws_lambda_function.create_link.function_name

  # Grant invocation permission specifically to the API Gateway service.
  principal = "apigateway.amazonaws.com"

  # Restrict invocation permission to this API Gateway HTTP API.
  source_arn = "${aws_apigatewayv2_api.url_shortener_api.execution_arn}/*/*"
}

# Allows API Gateway to invoke the resolve-link Lambda function.
resource "aws_lambda_permission" "allow_api_gateway_get_record_link" {
  # Assign a unique identifier to this Lambda resource-based policy statement.
  statement_id = "AllowAPIGatewayInvokeGetRecordLink"

  # Permit API Gateway to invoke the Lambda function.
  action = "lambda:InvokeFunction"

  # Grant the permission on the resolve-link Lambda function.
  function_name = aws_lambda_function.get_link_record.function_name

  # Grant invocation permission specifically to the API Gateway service.
  principal = "apigateway.amazonaws.com"

  # Restrict invocation permission to this API Gateway HTTP API.
  source_arn = "${aws_apigatewayv2_api.url_shortener_api.execution_arn}/*/*"
}


# Stores API Gateway access logs so requests and responses can be monitored.
resource "aws_cloudwatch_log_group" "api_gateway_access_logs" {
  # Use a descriptive name for the API Gateway access log group.
  name = "/aws/apigateway/url-shortener-api-access-logs"

  # Retain API access logs for seven days before CloudWatch deletes them.
  retention_in_days = 7

  # Apply the caller-provided tags to the CloudWatch log group.
  tags = var.tags
}

# Retrieves the AWS account ID of the identity running Terraform.
data "aws_caller_identity" "current" {}

# Builds the resource-based policy attached to the customer-managed KMS key.
data "aws_iam_policy_document" "dynamodb_kms" {
  # Preserve an administrative recovery path and enable IAM-based delegation.
  statement {
    # Give this policy statement a clear identifier.
    sid = "EnableIAMUserPermissions"

    # Allow the permissions defined in this statement.
    effect = "Allow"

    # Grant the AWS account principal authority over the KMS key.
    principals {
      type = "AWS"

      # Reference the root principal of the current AWS account.
      identifiers = [
        "arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"
      ]
    }

    # Allow full KMS administration through the account's IAM permissions.
    actions = [
      "kms:*"
    ]

    # Apply this statement to the KMS key represented by this key policy.
    resources = ["*"]
  }

  # Allow authorized application roles to use this key only through DynamoDB.
  statement {
    # Give this DynamoDB-specific key usage statement a clear identifier.
    sid = "AllowDynamoDBKeyUsage"

    # Allow the permissions defined in this statement.
    effect = "Allow"

    # Grant key usage to the two Lambda execution roles.
    principals {
      type = "AWS"

      # Restrict key usage to the create-link and resolve-link Lambda roles.
      identifiers = [
        aws_iam_role.create_link_lambda_role.arn,
        aws_iam_role.get_link_record_lambda_role.arn
      ]
    }

    # Allow only the KMS operations DynamoDB may require for encrypted table access.
    actions = [
      "kms:Encrypt",
      "kms:Decrypt",
      "kms:ReEncrypt*",
      "kms:GenerateDataKey*",
      "kms:DescribeKey",
      "kms:CreateGrant"
    ]

    # Apply this statement to the KMS key represented by this key policy.
    resources = ["*"]

    # Prevent the Lambda roles from using the key directly outside DynamoDB.
    condition {
      # Match DynamoDB service endpoints across AWS regions.
      test = "StringLike"

      # Restrict key usage based on the AWS service making the KMS request.
      variable = "kms:ViaService"

      # Permit key usage only when the request is made through DynamoDB.
      values = ["dynamodb.*.amazonaws.com"]
    }
  }
}

# Creates the customer-managed KMS key used to encrypt the DynamoDB table.
resource "aws_kms_key" "dynamodb" {
  # Describe the purpose of the key for easier identification in AWS.
  description = "Customer-managed KMS key for URL shortener DynamoDB encryption."

  # Enable automatic annual rotation of the KMS key material.
  enable_key_rotation = true

  # Require a waiting period before AWS permanently deletes the KMS key.
  deletion_window_in_days = 7

  # Attach the generated KMS key policy to this key to control who can administer
  # and use it, including restricting application key usage to DynamoDB.
  policy = data.aws_iam_policy_document.dynamodb_kms.json

  # Apply the caller-provided tags to the KMS key.
  tags = var.tags
}


# Creates a friendly alias for the customer-managed KMS key.
resource "aws_kms_alias" "dynamodb" {
  # Use the caller-provided alias name for the KMS key.
  name = var.kms_alias

  # Associate the alias with the URL shortener DynamoDB encryption key.
  target_key_id = aws_kms_key.dynamodb.key_id
}

# Defines the least-privilege DynamoDB permissions required by the create-link Lambda.
data "aws_iam_policy_document" "create_link_dynamodb" {
  statement {
    # Allow the create-link Lambda to perform the permitted DynamoDB action.
    effect = "Allow"

    # Permit only item creation; the create-link Lambda does not need read or delete access.
    actions = [
      "dynamodb:PutItem",
    ]

    # Restrict write access to this project's URL-shortener table.
    resources = [
      aws_dynamodb_table.link_records.arn,
    ]
  }
}

# Creates the IAM policy containing the create-link Lambda's DynamoDB permissions.
resource "aws_iam_policy" "create_link_dynamodb" {
  # Convert the generated IAM policy document into the JSON required by AWS IAM.
  policy = data.aws_iam_policy_document.create_link_dynamodb.json
}

# Attaches the DynamoDB write policy to the create-link Lambda execution role.
resource "aws_iam_role_policy_attachment" "create_link_dynamodb" {
  # Attach the policy only to the execution role used by the create-link Lambda.
  role = aws_iam_role.create_link_lambda_role.name

  # Grant the role the least-privilege DynamoDB write policy defined above.
  policy_arn = aws_iam_policy.create_link_dynamodb.arn
}


# Defines the least-privilege DynamoDB permissions required by the resolve-link Lambda.
data "aws_iam_policy_document" "resolve_link_dynamodb" {
  statement {
    # Allow the resolve-link Lambda to perform the permitted DynamoDB action.
    effect = "Allow"

    # Permit only direct item reads; the resolver does not need write or delete access.
    actions = [
      "dynamodb:GetItem",
    ]

    # Restrict read access to this project's URL-shortener table.
    resources = [
      aws_dynamodb_table.link_records.arn,
    ]
  }
}

# Creates the IAM policy containing the resolve-link Lambda's DynamoDB permissions.
resource "aws_iam_policy" "resolve_link_dynamodb" {
  # Convert the generated IAM policy document into the JSON required by AWS IAM.
  policy = data.aws_iam_policy_document.resolve_link_dynamodb.json
}

# Attaches the DynamoDB read policy to the resolve-link Lambda execution role.
resource "aws_iam_role_policy_attachment" "resolve_link_dynamodb" {
  # Attach the policy only to the execution role used by the resolve-link Lambda.
  role = aws_iam_role.get_link_record_lambda_role.name

  # Grant the role the least-privilege DynamoDB read policy defined above.
  policy_arn = aws_iam_policy.resolve_link_dynamodb.arn
}

# Explicitly manage the create-link Lambda log group so Terraform controls
# log retention instead of leaving the default indefinite retention period.
resource "aws_cloudwatch_log_group" "create_link" {
  # Match Lambda's standard CloudWatch log group naming convention.
  name = "/aws/lambda/${var.create_lambda_name}"

  # Retain application logs for seven days to limit unnecessary log storage.
  retention_in_days = 7

  # Apply the module's common resource tags.
  tags = var.tags
}

# Explicitly manage the resolve-link Lambda log group so Terraform controls
# log retention instead of leaving the default indefinite retention period.
resource "aws_cloudwatch_log_group" "resolve_link" {
  # Match Lambda's standard CloudWatch log group naming convention.
  name = "/aws/lambda/${var.resolve_lambda_name}"

  # Retain application logs for seven days to limit unnecessary log storage.
  retention_in_days = 7

  # Apply the module's common resource tags.
  tags = var.tags
}
